name: CI
on: [push,pull_request]
jobs:
  ci:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Install dependences 
        run: npm install
      - name: Run tests 
        run: |
          npm run test-MVR-loc
          npm run test-GBD-loc
          npm run test-MADC-loc
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}